import "./globals.css";
import { Inter } from "next/font/google";
// app/layout.jsx
import { DemoProvider } from "./components/DemoContext";
import RoleLayout from "./components/RoleLayout";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.className} scroll-smooth`}>
      <body>
        <DemoProvider>
          <RoleLayout>{children}</RoleLayout>
        </DemoProvider>
      </body>
    </html>
  );
}
